apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "request-processor.fullname" . }}-config
  labels:
    {{- include "request-processor.labels" . | nindent 4 }}
data:
  .env: |
    PORT=4000
    TARGET_ENDPOINT={{ .Values.targetEndpoint }}
    LOG_LEVEL={{ .Values.appConfig.logLevel }}