apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "request-processor.fullname" . }}
  labels:
    {{- include "request-processor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "request-processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "request-processor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          volumeMounts:
            - name: app-config
              mountPath: /app/.env
              subPath: .env
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 300
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 300
          env:
            - name: NODE_ENV
              value: "production"
      volumes:
        - name: app-config
          configMap:
            name: {{ include "request-processor.fullname" . }}-config
            items:
            - key: .env
              path: .env